✨ 网络测试页面延迟后增加info图标
BeyondDimension/SteamTools pull request #3544
Opened 2024-11-19 07:55 UTC by luojunyuan

![image](https://github.com/user-attachments/assets/ca0bcf21-54eb-47ef-b537-13ac44f1d45c)

2024-11-20 06:35 UTC, luojunyuan commented
修改保持最小变更，在不改变原有业务逻辑的基础上进行，不做任何重构。

2024-11-21 03:39 UTC, luojunyuan commented
实现的效果：
![{F1930BAF-EFFA-4F8D-B04F-5D5209D8E8C0}](https://github.com/user-attachments/assets/50964547-2c79-4a38-b47d-1e3934b57201)
这里 `ASFService.Current.DownloadASFAsync()` 方法传入 CancelToken 取消后没办法再度重新下载，就没设置取消按钮了。

2024-11-21 03:50 UTC, luojunyuan commented on src/BD.WTTS.Client.Plugins.ArchiSteamFarmPlus/UI/ViewModels/ArchiSteamFarmExePathSettingsPageViewModel.cs
> +                ASFService.Current.DownloadASFAsync(progress: progress);
这里 ASFService.Current.DownloadASFAsync() 方法传入 CancelToken 取消后没办法再度重新下载，就没设置取消按钮了。

2024-11-21 17:02 UTC, rmbadmin requested changes
StringNotEmptyToVisibilityConverter 是不必要的添加 应使用已有的 IsNullConverter

2024-11-22 02:23 UTC, luojunyuan reviewed
done.

2024-11-25 09:24 UTC, rmbadmin approved these changes

2024-11-25 09:25 UTC, merged